import type {
  DaysSupplyBreakdownEntry,
  HoldingCostBucket,
  NeedsActionBreakdown,
  SoldVehicle,
  TimeToMarketBucket,
  Vehicle,
} from "./types"

// A fixed reference instant, not `new Date()` — mock data is computed once at
// module scope, which runs independently on the server (SSR) and the client
// (hydration). Anything time-dependent must be deterministic or the two
// renders disagree and React throws a hydration-mismatch error.
const MOCK_NOW = new Date("2026-09-08T15:00:00.000Z")

function daysAgo(days: number): string {
  const d = new Date(MOCK_NOW)
  d.setDate(d.getDate() - days)
  return d.toISOString()
}

export const VEHICLES: Vehicle[] = [
  {
    id: "v-2100",
    stockNumber: "STK-2100",
    vin: "VIN1234567889000",
    year: 2025,
    make: "Hyundai",
    model: "Tucson",
    trim: "SE",
    mileage: 9412,
    bodyType: "Midsize SUV",
    exteriorColor: "Phantom Black",
    interiorTrim: "Black Cloth",
    photoUrl: null,
    price: 34900,
    daysSupply: 72,
    daysSupplyStatus: "overstocked",
    source: { channel: "IMS", detail: "DMS feed" },
    ageDays: 7,
    listedAt: daysAgo(7),
    holdingCost: 229,
    salesInquiries: 2,
    condition: "new",
    needsAction: { noPhotos: true, needsPromotion: false, notLiveYet: false },
  },
  {
    id: "v-2101",
    stockNumber: "STK-2101",
    vin: "VIN4T1BF3EK2AU123",
    year: 2022,
    make: "Toyota",
    model: "Camry",
    trim: "XSE",
    mileage: 42180,
    bodyType: "Midsize Sedan",
    photoUrl: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400&q=60",
    price: 25400,
    daysSupply: 39,
    daysSupplyStatus: "on_target",
    source: { channel: "Website", detail: "Website scrape" },
    ageDays: 12,
    listedAt: daysAgo(12),
    holdingCost: 499,
    salesInquiries: 5,
    condition: "pre-owned",
    needsAction: { noPhotos: false, needsPromotion: false, notLiveYet: false },
  },
  {
    id: "v-2102",
    stockNumber: "STK-2102",
    vin: "VIN1HGCV1F34LA456",
    year: 2020,
    make: "Honda",
    model: "Accord",
    trim: "Sport",
    mileage: 89340,
    bodyType: "Midsize Sedan",
    photoUrl: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=400&q=60",
    price: 33200,
    daysSupply: 39,
    daysSupplyStatus: "on_target",
    source: { channel: "Marketplace", detail: "Facebook" },
    ageDays: 18,
    listedAt: daysAgo(18),
    holdingCost: 1029,
    holdingCostNote: { kind: "loss", text: "- $45 loss" },
    salesInquiries: 1,
    condition: "pre-owned",
    needsAction: { noPhotos: false, needsPromotion: true, notLiveYet: false },
  },
  {
    id: "v-2103",
    stockNumber: "STK-2103",
    vin: "VIN3GCUKREC0PG789",
    year: 2023,
    make: "Chevrolet",
    model: "Silverado 1500",
    mileage: 12760,
    bodyType: "Full-size Truck",
    photoUrl: "https://images.unsplash.com/photo-1594502184342-2e12f877aa73?w=400&q=60",
    price: 32750,
    daysSupply: 54,
    daysSupplyStatus: "on_target",
    source: { channel: "Marketplace", detail: "AutoTrader wholesale" },
    ageDays: 24,
    listedAt: daysAgo(24),
    holdingCost: 748,
    holdingCostNote: { kind: "add_cost_price", text: "+ Add Cost Price" },
    salesInquiries: 3,
    condition: "pre-owned",
    needsAction: { noPhotos: false, needsPromotion: false, notLiveYet: false },
  },
  {
    id: "v-2104",
    stockNumber: "STK-2104",
    vin: "VINWBA5R1C52KAJ012",
    year: 2019,
    make: "BMW",
    model: "3 Series",
    trim: "330i",
    mileage: 156920,
    bodyType: "Midsize SUV",
    photoUrl: null,
    price: 78900,
    daysSupply: 72,
    daysSupplyStatus: "overstocked",
    source: { channel: "IMS", detail: "DMS feed" },
    ageDays: 31,
    listedAt: daysAgo(31),
    holdingCost: 312,
    holdingCostNote: { kind: "margin", text: "58% of $3200 margin" },
    salesInquiries: 0,
    condition: "pre-owned",
    needsAction: { noPhotos: true, needsPromotion: false, notLiveYet: true },
  },
  {
    id: "v-2105",
    stockNumber: "STK-2105",
    vin: "VIN1C4RJKBG7N8345",
    year: 2022,
    make: "Jeep",
    model: "Grand Cherokee L",
    mileage: 63410,
    bodyType: "Sport Coupe",
    photoUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=400&q=60",
    price: 36400,
    daysSupply: 28,
    daysSupplyStatus: "on_target",
    source: { channel: "IMS", detail: "DMS feed" },
    ageDays: 40,
    listedAt: daysAgo(40),
    holdingCost: 184,
    holdingCostNote: { kind: "margin", text: "24% of $6100 margin" },
    salesInquiries: 2,
    condition: "pre-owned",
    needsAction: { noPhotos: false, needsPromotion: true, notLiveYet: false },
  },
  {
    id: "v-2106",
    stockNumber: "STK-2106",
    vin: "VIN5NPE24AF1FH1122",
    year: 2024,
    make: "Kia",
    model: "Sportage",
    trim: "LX",
    mileage: 5210,
    bodyType: "Compact SUV",
    photoUrl: "https://images.unsplash.com/photo-1533106418989-88406c7cc8ca?w=400&q=60",
    price: 27800,
    daysSupply: 18,
    daysSupplyStatus: "understocked",
    source: { channel: "IMS", detail: "DMS feed" },
    ageDays: 5,
    listedAt: daysAgo(5),
    holdingCost: 175,
    salesInquiries: 6,
    condition: "new",
    needsAction: { noPhotos: false, needsPromotion: false, notLiveYet: false },
  },
  {
    id: "v-2107",
    stockNumber: "STK-2107",
    vin: "VIN1FTFW1E5XJFA5566",
    year: 2021,
    make: "Ford",
    model: "F-150",
    trim: "XLT",
    mileage: 47800,
    bodyType: "Full-size Truck",
    photoUrl: null,
    price: 38950,
    daysSupply: 61,
    daysSupplyStatus: "overstocked",
    source: { channel: "Website", detail: "Website scrape" },
    ageDays: 64,
    listedAt: daysAgo(64),
    holdingCost: 3392,
    holdingCostNote: { kind: "loss", text: "- $180 loss" },
    salesInquiries: 1,
    condition: "pre-owned",
    needsAction: { noPhotos: true, needsPromotion: true, notLiveYet: false },
  },
  {
    id: "v-2108",
    stockNumber: "STK-2108",
    vin: "VIN2C4RC1BG3ER7788",
    year: 2020,
    make: "Chrysler",
    model: "Pacifica",
    trim: "Touring L",
    mileage: 71200,
    bodyType: "Minivan",
    photoUrl: "https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=400&q=60",
    price: 24600,
    daysSupply: 45,
    daysSupplyStatus: "on_target",
    source: { channel: "Marketplace", detail: "Craigslist" },
    ageDays: 44,
    listedAt: daysAgo(44),
    holdingCost: 2200,
    salesInquiries: 0,
    condition: "pre-owned",
    needsAction: { noPhotos: false, needsPromotion: false, notLiveYet: false },
  },
  {
    id: "v-2109",
    stockNumber: "STK-2109",
    vin: "VIN3VW2B7AJ9EM9944",
    year: 2023,
    make: "Volkswagen",
    model: "Jetta",
    trim: "SE",
    mileage: 15600,
    bodyType: "Compact Sedan",
    photoUrl: "https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=400&q=60",
    price: 21300,
    daysSupply: 22,
    daysSupplyStatus: "on_target",
    source: { channel: "IMS", detail: "DMS feed" },
    ageDays: 3,
    listedAt: daysAgo(3),
    holdingCost: 87,
    salesInquiries: 3,
    condition: "new",
    needsAction: { noPhotos: false, needsPromotion: false, notLiveYet: false },
  },
  {
    id: "v-2110",
    stockNumber: "STK-2110",
    vin: "VIN1G1ZD5ST0LF2233",
    year: 2019,
    make: "Chevrolet",
    model: "Malibu",
    trim: "LT",
    mileage: 98230,
    bodyType: "Midsize Sedan",
    photoUrl: null,
    price: 15900,
    daysSupply: 68,
    daysSupplyStatus: "overstocked",
    source: { channel: "Marketplace", detail: "Facebook" },
    ageDays: 71,
    listedAt: daysAgo(71),
    holdingCost: 3692,
    holdingCostNote: { kind: "loss", text: "- $320 loss" },
    salesInquiries: 0,
    condition: "pre-owned",
    needsAction: { noPhotos: true, needsPromotion: true, notLiveYet: true },
  },
  {
    id: "v-2111",
    stockNumber: "STK-2111",
    vin: "VIN5YJ3E1EA8KF4455",
    year: 2024,
    make: "Tesla",
    model: "Model 3",
    trim: "Long Range",
    mileage: 2100,
    bodyType: "Compact Sedan",
    photoUrl: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400&q=60",
    price: 41200,
    daysSupply: 14,
    daysSupplyStatus: "understocked",
    source: { channel: "IMS", detail: "DMS feed" },
    ageDays: 2,
    listedAt: daysAgo(2),
    holdingCost: 58,
    salesInquiries: 8,
    condition: "new",
    needsAction: { noPhotos: false, needsPromotion: false, notLiveYet: false },
  },
  {
    id: "v-2112",
    stockNumber: "STK-2112",
    vin: "VIN1FMCU9J9XKUA6677",
    year: 2022,
    make: "Ford",
    model: "Escape",
    trim: "SEL",
    mileage: 33400,
    bodyType: "Compact SUV",
    photoUrl: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=400&q=60",
    price: 26750,
    daysSupply: 31,
    daysSupplyStatus: "on_target",
    source: { channel: "Website", detail: "Website scrape" },
    ageDays: 9,
    listedAt: daysAgo(9),
    holdingCost: 450,
    salesInquiries: 2,
    condition: "pre-owned",
    needsAction: { noPhotos: false, needsPromotion: false, notLiveYet: false },
  },
  {
    id: "v-2113",
    stockNumber: "STK-2113",
    vin: "VIN2T3RFREV9LW8899",
    year: 2020,
    make: "Toyota",
    model: "RAV4",
    trim: "XLE",
    mileage: 61500,
    bodyType: "Compact SUV",
    photoUrl: "https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=400&q=60",
    price: 27400,
    daysSupply: 52,
    daysSupplyStatus: "on_target",
    source: { channel: "IMS", detail: "DMS feed" },
    ageDays: 47,
    listedAt: daysAgo(47),
    holdingCost: 2350,
    salesInquiries: 4,
    condition: "pre-owned",
    needsAction: { noPhotos: false, needsPromotion: true, notLiveYet: false },
  },
  {
    id: "v-2114",
    stockNumber: "STK-2114",
    vin: "VIN1G6DW677360122",
    year: 2018,
    make: "Cadillac",
    model: "CTS",
    trim: "Luxury",
    mileage: 84200,
    bodyType: "Full-size Sedan",
    photoUrl: null,
    price: 19800,
    daysSupply: 66,
    daysSupplyStatus: "overstocked",
    source: { channel: "Marketplace", detail: "AutoTrader wholesale" },
    ageDays: 58,
    listedAt: daysAgo(58),
    holdingCost: 2900,
    holdingCostNote: { kind: "add_cost_price", text: "+ Add Cost Price" },
    salesInquiries: 0,
    condition: "pre-owned",
    needsAction: { noPhotos: true, needsPromotion: false, notLiveYet: false },
  },
  {
    id: "v-2115",
    stockNumber: "STK-2115",
    vin: "VIN3N1AB7AP9GY3344",
    year: 2023,
    make: "Nissan",
    model: "Sentra",
    trim: "SV",
    mileage: 19800,
    bodyType: "Compact Sedan",
    photoUrl: "https://images.unsplash.com/photo-1494905998402-395d579af36f?w=400&q=60",
    price: 19900,
    daysSupply: 26,
    daysSupplyStatus: "on_target",
    source: { channel: "IMS", detail: "DMS feed" },
    ageDays: 15,
    listedAt: daysAgo(15),
    holdingCost: 750,
    salesInquiries: 3,
    condition: "new",
    needsAction: { noPhotos: false, needsPromotion: false, notLiveYet: false },
  },
  {
    id: "v-2116",
    stockNumber: "STK-2116",
    vin: "VIN1GNSKBKC7KR4411",
    year: 2021,
    make: "Chevrolet",
    model: "Tahoe",
    trim: "LT",
    mileage: 52300,
    bodyType: "Full-size SUV",
    photoUrl: "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400&q=60",
    price: 49500,
    daysSupply: 43,
    daysSupplyStatus: "on_target",
    source: { channel: "Website", detail: "Website scrape" },
    ageDays: 22,
    listedAt: daysAgo(22),
    holdingCost: 1100,
    salesInquiries: 2,
    condition: "pre-owned",
    needsAction: { noPhotos: false, needsPromotion: false, notLiveYet: false },
  },
  {
    id: "v-2117",
    stockNumber: "STK-2117",
    vin: "VIN1HD1KB4197Y2233",
    year: 2022,
    make: "Subaru",
    model: "Outback",
    trim: "Premium",
    mileage: 29700,
    bodyType: "Crossover",
    photoUrl: null,
    price: 29200,
    daysSupply: 34,
    daysSupplyStatus: "on_target",
    source: { channel: "Marketplace", detail: "Facebook" },
    ageDays: 26,
    listedAt: daysAgo(26),
    holdingCost: 1300,
    salesInquiries: 3,
    condition: "pre-owned",
    needsAction: { noPhotos: true, needsPromotion: false, notLiveYet: false },
  },
  {
    id: "v-2118",
    stockNumber: "STK-2118",
    vin: "VIN1FA6P8TH8K5511",
    year: 2024,
    make: "Ford",
    model: "Mustang",
    trim: "GT",
    mileage: 1250,
    bodyType: "Sport Coupe",
    photoUrl: "https://images.unsplash.com/photo-1494905998402-395d579af36f?w=400&q=60",
    price: 46800,
    daysSupply: 11,
    daysSupplyStatus: "understocked",
    source: { channel: "IMS", detail: "DMS feed" },
    ageDays: 1,
    listedAt: daysAgo(1),
    holdingCost: 42,
    salesInquiries: 9,
    condition: "new",
    needsAction: { noPhotos: false, needsPromotion: false, notLiveYet: true },
  },
  {
    id: "v-2119",
    stockNumber: "STK-2119",
    vin: "VIN1J4GZ58S6YC1122",
    year: 2017,
    make: "Jeep",
    model: "Wrangler",
    trim: "Sport",
    mileage: 102400,
    bodyType: "Compact SUV",
    photoUrl: null,
    price: 22400,
    daysSupply: 75,
    daysSupplyStatus: "overstocked",
    source: { channel: "Marketplace", detail: "AutoTrader wholesale" },
    ageDays: 82,
    listedAt: daysAgo(82),
    holdingCost: 4756,
    holdingCostNote: { kind: "loss", text: "- $410 loss" },
    salesInquiries: 1,
    condition: "pre-owned",
    needsAction: { noPhotos: true, needsPromotion: true, notLiveYet: false },
  },
  {
    id: "v-2120",
    stockNumber: "STK-2120",
    vin: "VIN1N4AL3AP0FC1188",
    year: 2023,
    make: "Nissan",
    model: "Altima",
    trim: "SR",
    mileage: 18900,
    bodyType: "Midsize Sedan",
    photoUrl: "https://images.unsplash.com/photo-1550355291-bbee04a92027?w=400&q=60",
    price: 24700,
    daysSupply: 29,
    daysSupplyStatus: "on_target",
    source: { channel: "IMS", detail: "DMS feed" },
    ageDays: 6,
    listedAt: daysAgo(6),
    holdingCost: 200,
    salesInquiries: 2,
    condition: "new",
    needsAction: { noPhotos: false, needsPromotion: false, notLiveYet: false },
  },
  {
    id: "v-2121",
    stockNumber: "STK-2121",
    vin: "VIN1GCUYDED9RZ1199",
    year: 2024,
    make: "GMC",
    model: "Sierra 1500",
    trim: "SLE",
    mileage: 6800,
    bodyType: "Full-size Truck",
    photoUrl: "https://images.unsplash.com/photo-1615906655593-ad0386982a0f?w=400&q=60",
    price: 45300,
    daysSupply: 20,
    daysSupplyStatus: "understocked",
    source: { channel: "IMS", detail: "DMS feed" },
    ageDays: 8,
    listedAt: daysAgo(8),
    holdingCost: 280,
    salesInquiries: 7,
    condition: "new",
    needsAction: { noPhotos: false, needsPromotion: false, notLiveYet: false },
  },
  {
    id: "v-2122",
    stockNumber: "STK-2122",
    vin: "VIN2HGFC2F59JH2244",
    year: 2018,
    make: "Honda",
    model: "Civic",
    trim: "EX",
    mileage: 76500,
    bodyType: "Compact Sedan",
    photoUrl: "https://images.unsplash.com/photo-1583267746897-2cf415887172?w=400&q=60",
    price: 16800,
    daysSupply: 41,
    daysSupplyStatus: "on_target",
    source: { channel: "Website", detail: "Website scrape" },
    ageDays: 35,
    listedAt: daysAgo(35),
    holdingCost: 1750,
    holdingCostNote: { kind: "margin", text: "31% of $2100 margin" },
    salesInquiries: 4,
    condition: "pre-owned",
    needsAction: { noPhotos: false, needsPromotion: true, notLiveYet: false },
  },
  {
    id: "v-2123",
    stockNumber: "STK-2123",
    vin: "VIN5TDKZ3DC1LS1177",
    year: 2020,
    make: "Toyota",
    model: "Highlander",
    trim: "Limited",
    mileage: 58900,
    bodyType: "Full-size SUV",
    photoUrl: null,
    price: 34100,
    daysSupply: 63,
    daysSupplyStatus: "overstocked",
    source: { channel: "Marketplace", detail: "Facebook" },
    ageDays: 55,
    listedAt: daysAgo(55),
    holdingCost: 2750,
    salesInquiries: 0,
    condition: "pre-owned",
    needsAction: { noPhotos: true, needsPromotion: false, notLiveYet: false },
  },
  {
    id: "v-2124",
    stockNumber: "STK-2124",
    vin: "VIN1FTEW1EP0JFA9933",
    year: 2019,
    make: "Ford",
    model: "F-250",
    trim: "Lariat",
    mileage: 68200,
    bodyType: "Full-size Truck",
    photoUrl: "https://images.unsplash.com/photo-1533106418989-88406c7cc8ca?w=400&q=60",
    price: 42900,
    daysSupply: 48,
    daysSupplyStatus: "on_target",
    source: { channel: "IMS", detail: "DMS feed" },
    ageDays: 19,
    listedAt: daysAgo(19),
    holdingCost: 900,
    salesInquiries: 2,
    condition: "pre-owned",
    needsAction: { noPhotos: false, needsPromotion: false, notLiveYet: false },
  },
]

export const SOLD_VEHICLES: SoldVehicle[] = [
  {
    id: "sold-1",
    stockNumber: "STK-1980",
    vin: "VIN1FA6P8CF7K5501",
    year: 2023,
    make: "Ford",
    model: "Mustang",
    trim: "EcoBoost",
    bodyType: "Sport Coupe",
    photoUrl: "https://images.unsplash.com/photo-1494905998402-395d579af36f?w=400&q=60",
    soldPrice: 33900,
    daysToSell: 14,
    soldAt: daysAgo(9),
    buyerSource: { channel: "IMS", detail: "DMS feed" },
  },
  {
    id: "sold-2",
    stockNumber: "STK-1975",
    vin: "VIN2T1BURHE0JC1234",
    year: 2021,
    make: "Toyota",
    model: "Corolla",
    trim: "LE",
    bodyType: "Compact Sedan",
    photoUrl: "https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=400&q=60",
    soldPrice: 18700,
    daysToSell: 22,
    soldAt: daysAgo(16),
    buyerSource: { channel: "Website", detail: "Website scrape" },
  },
  {
    id: "sold-3",
    stockNumber: "STK-1968",
    vin: "VIN1GNSKBKC0KR2244",
    year: 2020,
    make: "Chevrolet",
    model: "Tahoe",
    trim: "LT",
    bodyType: "Full-size SUV",
    photoUrl: "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400&q=60",
    soldPrice: 44300,
    daysToSell: 31,
    soldAt: daysAgo(25),
    buyerSource: { channel: "Marketplace", detail: "AutoTrader wholesale" },
  },
  {
    id: "sold-4",
    stockNumber: "STK-1959",
    vin: "VIN3VW2B7AJ0EM7788",
    year: 2022,
    make: "Volkswagen",
    model: "Jetta",
    trim: "S",
    bodyType: "Compact Sedan",
    photoUrl: "https://images.unsplash.com/photo-1550355291-bbee04a92027?w=400&q=60",
    soldPrice: 19200,
    daysToSell: 9,
    soldAt: daysAgo(40),
    buyerSource: { channel: "IMS", detail: "DMS feed" },
  },
]

export function getDaysSupplyBreakdown(vehicles: Vehicle[]): DaysSupplyBreakdownEntry[] {
  const byType = new Map<string, { totalDays: number; count: number; status: Record<string, number> }>()
  for (const v of vehicles) {
    const entry = byType.get(v.bodyType) ?? { totalDays: 0, count: 0, status: {} }
    entry.totalDays += v.daysSupply
    entry.count += 1
    entry.status[v.daysSupplyStatus] = (entry.status[v.daysSupplyStatus] ?? 0) + 1
    byType.set(v.bodyType, entry)
  }

  const onTarget: { name: string; days: number }[] = []
  const overstocked: { name: string; days: number }[] = []

  for (const [name, entry] of byType) {
    const avgDays = Math.round(entry.totalDays / entry.count)
    const majorityOverstocked = (entry.status.overstocked ?? 0) > (entry.status.on_target ?? 0) + (entry.status.understocked ?? 0)
    if (majorityOverstocked) {
      overstocked.push({ name, days: avgDays })
    } else {
      onTarget.push({ name, days: avgDays })
    }
  }

  return [
    { status: "on_target", typeCount: onTarget.length, bodyTypes: onTarget },
    { status: "overstocked", typeCount: overstocked.length, bodyTypes: overstocked },
  ]
}

export function getTimeToMarketBuckets(vehicles: Vehicle[]): TimeToMarketBucket[] {
  const under3 = vehicles.filter((v) => v.ageDays < 3).length
  const between3And6 = vehicles.filter((v) => v.ageDays >= 3 && v.ageDays <= 6).length
  const over6 = vehicles.filter((v) => v.ageDays > 6).length
  return [
    { label: "<3 days", count: under3 },
    { label: "3-6 days", count: between3And6 },
    { label: "6+ days", count: over6 },
  ]
}

export function getHoldingCostBuckets(vehicles: Vehicle[]): HoldingCostBucket[] {
  const under100 = vehicles.filter((v) => v.holdingCost < 100).length
  const between100And500 = vehicles.filter((v) => v.holdingCost >= 100 && v.holdingCost <= 500).length
  const over500 = vehicles.filter((v) => v.holdingCost > 500).length
  return [
    { label: "< $100", count: under100 },
    { label: "$100 – $500", count: between100And500 },
    { label: "> $500", count: over500 },
  ]
}

export function getNeedsActionBreakdown(vehicles: Vehicle[]): NeedsActionBreakdown {
  return {
    studioOs: {
      noPhotos: vehicles.filter((v) => v.needsAction.noPhotos).length,
      needsPromotion: vehicles.filter((v) => v.needsAction.needsPromotion).length,
      notLiveYet: vehicles.filter((v) => v.needsAction.notLiveYet).length,
    },
    // Vini AI (conversational sales/service agent) action items are a separate
    // workstream from Studio OS merchandising and aren't derived from vehicle
    // records — seeded with representative counts for this mock.
    viniAi: { sales: 9, services: 6, receptions: 3 },
  }
}

export function needsAnyAction(v: Vehicle): boolean {
  return v.needsAction.noPhotos || v.needsAction.needsPromotion || v.needsAction.notLiveYet
}

/** Threshold above which Vini's logged sales inquiries count as "high demand". */
export const HIGH_DEMAND_THRESHOLD = 4

export function isHighDemand(v: Vehicle): boolean {
  return v.salesInquiries >= HIGH_DEMAND_THRESHOLD
}

export function totalDaysSupply(vehicles: Vehicle[]): number {
  if (vehicles.length === 0) return 0
  return Math.round(vehicles.reduce((sum, v) => sum + v.daysSupply, 0) / vehicles.length)
}

export function totalTimeToMarket(vehicles: Vehicle[]): number {
  if (vehicles.length === 0) return 0
  return Math.round(vehicles.reduce((sum, v) => sum + v.ageDays, 0) / vehicles.length)
}

export function totalHoldingCost(vehicles: Vehicle[]): number {
  return vehicles.reduce((sum, v) => sum + v.holdingCost, 0)
}
